org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_version=21.1.228

moddev_version=2.0.112
neogradle_version=7.0.192

mod_id=betterend

archives_base_name=BetterEnd-reimagined
mod_version=21.0.26

maven_group=org.betterx

wthit_version=12.8.3
emi_version=1.1.8+1.21
jei_version=19.21.0.247
jade_version=15.10.5+neoforge
biolith_modrinth_version_id=1ZfKhpFg

curseforge_id=413596
modrinth_id=betterend

# Dependency metadata for publishing helpers
required_dependencies=["biolith"]
optional_dependencies=["emi","jei","jade"]
