modLoader="javafml"
loaderVersion="[1,)"
license="MIT (CC BY-NC-SA 4.0 for some Assets)"
issueTrackerURL="https://github.com/ne-PobiH/BetterEnd_Neoforge_more_bugs_fr/tree/absolute"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Better End reimagined"
description="More content for The End dimension, including new biomes, plants, mobs, mechanics, terrain generation and more."
authors="quiqueck, paulevs (original author), Bulldog83, Edos, Yuki, Seaward, Firel, Raijin, mapih, kinron"
displayURL="https://www.curseforge.com/minecraft/mc-mods/betterend"
logoFile="assets/betterend/icon.png"

[[mods]]
modId="all_is_better_lib"
version="${version}"
displayName="AiBlib"
description="Embedded BetterEnd runtime library bundle based on BCLib, WunderLib and WorldWeaver."
authors="quiqueck, paulevs, BetterX contributors"
displayURL="https://github.com/ne-PobiH/BetterEnd_Neoforge_more_bugs_fr/tree/absolute"
logoFile="assets/all_is_better_lib/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="all_is_better_lib"
mandatory=true
versionRange="[${version},)"
ordering="NONE"
side="BOTH"

[[dependencies.all_is_better_lib]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.all_is_better_lib]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="betterend.mixins.common.json"

[[mixins]]
config="betterend.mixins.client.json"

[[mixins]]
config="all_is_better_lib.bclib.mixins.common.json"

[[mixins]]
config="all_is_better_lib.bclib.mixins.client.json"

[[mixins]]
config="all_is_better_lib.wover.core.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.event.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.tag.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.item.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.block.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.poi.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.recipe.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.potion.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.surface.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.biome.mixins.common.json"

[[mixins]]
config="all_is_better_lib.wover.generator.mixins.common.json"

[modproperties.${mod_id}]
updater_icon="icon_updater.png"

[modproperties.${mod_id}.downloads]
modrinth="https://modrinth.com/mod/betterend"
curseforge="https://www.curseforge.com/minecraft/mc-mods/betterend"

[modproperties.${mod_id}.modupdater]
strategy="curseforge"
projectID=413596
